from typing import Dict

CROATIAN: Dict[str, str] = {
    "EA": "Eurozona (u tom trenutku)",
    "EA19": "Eurozona (19 država)",
    "EA18": "Eurozona (18 država)",
    "EU": "Europska unija (u tom trenutku)",
    "EU28": "Europska unija (28 država)",
    "BE": "Belgija",
    "BG": "Bugarska",
    "CZ": "Češka",
    "DK": "Danska",
    "DE": "Njemačka",
    "EE": "Estonija",
    "IE": "Irska",
    "EL": "Grčka",
    "ES": "Španjolska",
    "FR": "Francuska",
    "HR": "Hrvatska",
    "IT": "Italija",
    "CY": "Cipar",
    "LI": "Liechtenstein",
    "LV": "Latvija",
    "LT": "Litva",
    "LU": "Luksemburg",
    "HU": "Mađarska",
    "MT": "Malta",
    "NL": "Nizozemska",
    "AT": "Austrija",
    "PL": "Poljska",
    "PT": "Portugal",
    "RO": "Rumunjska",
    "SI": "Slovenija",
    "SK": "Slovačka",
    "FI": "Finska",
    "SE": "Švedska",
    "UK": "Velika Britanija",
    "IS": "Island",
    "NE": "Norveška",
    "CH": "Švicarska",
    "MK": "Sjeverna Makedonija",
    "RS": "Srbija",
    "TR": "Turska",
    "US": "Sjedinjene Države",
}

ENGLISH: Dict[str, str] = {
    "EA": "Eurozone (at that point in time)",
    "EA19": "Eurozone (19 countries)",
    "EA18": "Eurozone (18 countries)",
    "EU": "European Union (at that point in time)",
    "EU28": "European Union (28 countries)",
    "BA": "Bosnia and Herzegovina",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "CZ": "Czechia",
    "DK": "Denmark",
    "DE": "Germany",
    "EE": "Estonia",
    "IE": "Ireland",
    "EL": "Greece",
    "ES": "Spain",
    "FR": "France",
    "HR": "Croatia",
    "IT": "Italy",
    "CY": "Cyprus",
    "LI": "Liechtenstein",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "HU": "Hungary",
    "MT": "Malta",
    "NL": "Netherlands",
    "AT": "Austria",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "FI": "Finland",
    "SE": "Sweden",
    "UK": "the United Kingdom",
    "IS": "Iceland",
    "NO": "Norway",
    "CH": "Switzerland",
    "MK": "North Macedonia",
    "RS": "Serbia",
    "TR": "Turkey",
    "US": "the United States",
}

FINNISH: Dict[str, str] = {
    "EA": "euroalue (kyseisellä ajanhetkellä)",
    "EA19": "euroalue (19 maata)",
    "EA18": "euroalue (18 maata)",
    "EU": "Euroopan unioni (kyseisellä ajanhetkellä)",
    "EU28": "Euroopan unioni (28 maata)",
    "BE": "Belgia",
    "BG": "Bulgaria",
    "CZ": "Tsekki",
    "DK": "Tanska",
    "DE": "Saksa",
    "EE": "Viro",
    "IE": "Irlanti",
    "EL": "Kreikka",
    "ES": "Espanja",
    "FR": "Ranska",
    "HR": "Kroatia",
    "IT": "Italia",
    "CY": "Kypros",
    "LI": "Liechtenstein",
    "LV": "Latvia",
    "LT": "Liettua",
    "LU": "Luxemburg",
    "HU": "Unkari",
    "MT": "Malta",
    "NL": "Alankomaat",
    "AT": "Itävalta",
    "PL": "Puola",
    "PT": "Portugali",
    "RO": "Romania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "FI": "Suomi",
    "SE": "Ruotsi",
    "UK": "Yhdistynyt Kuningaskunta",
    "IS": "Islanti",
    "NO": "Norja",
    "CH": "Sveitsi",
    "MK": "Pohjois-Makedonia",
    "RS": "Serbia",
    "TR": "Turkki",
    "US": "Yhdysvallat",
}

GERMAN: Dict[str, str] = {
    "EA": "Euro Gebiet (zu diesem Zeitpunkt)",
    "EA19": "Euro Gebiet (19 Länder)",
    "EA18": "Euro Gebiet (18 Länder)",
    "EU": "Europäische Union (zu diesem Zeitpunkt)",
    "EU28": "Europäische Union (28 Länder)",
    "BE": "Belgien",
    "BG": "Bulgarien",
    "CZ": "Tschechien",
    "DK": "Dänemark",
    "DE": "Deutschland",
    "EE": "Estland",
    "IE": "Irland",
    "EL": "Griechenland",
    "ES": "Spanien",
    "FR": "Frankreich",
    "HR": "Kroatien",
    "IT": "Italien",
    "CY": "Zypern",
    "LI": "Liechtenstein",
    "LV": "Lettland",
    "LT": "Litauen",
    "LU": "Luxemburg",
    "HU": "Ungarn",
    "MT": "Malta",
    "NL": "Niederlande",
    "AT": "Österreich",
    "PL": "Polen",
    "PT": "Portugal",
    "RO": "Rumänien",
    "SI": "Slowenien",
    "SK": "Slowakei",
    "FI": "Finnland",
    "SE": "Schweden",
    "UK": "Großbritannien",
    "IS": "Island",
    "NO": "Norwegen",
    "CH": "Schweiz",
    "MK": "Nordmakedonien",
    "RS": "Serbien",
    "TR": "Türkei",
    "US": "der Vereinigte Staaten",
}

RUSSIAN: Dict[str, str] = {
    "EA": "Еврозона (на тот момент)",
    "EA19": "Еврозона (19 стран)",
    "EA18": "Еврозона (18 стран)",
    "EU": "Европейский Союз (на тот момент)",
    "EU28": "Европейский Союз (28 стран)",
    "BA": "Босния и Герцеговина",
    "BE": "Бельгия",
    "BG": "Болгария",
    "CZ": "Чехия",
    "DK": "Дания",
    "DE": "Германия",
    "EE": "Эстония",
    "IE": "Ирландия",
    "EL": "Греция",
    "ES": "Испания",
    "FR": "Франция",
    "HR": "Хорватия",
    "IT": "Италия",
    "CY": "Кипр",
    "LI": "Лихтенштейн",
    "LV": "Латвия",
    "LT": "Литва",
    "LU": "Люксембург",
    "HU": "Венгрия",
    "MT": "Мальта",
    "NL": "Нидерланды",
    "AT": "Австрия",
    "PL": "Польша",
    "PT": "Португалия",
    "RO": "Румыния",
    "SI": "Словения",
    "SK": "Словакия",
    "FI": "Финляндия",
    "SE": "Швеция",
    "UK": "Соединенное Королевство",
    "IS": "Исландия",
    "NO": "Норвегия",
    "CH": "Швейцария",
    "MK": "Северная Македония",
    "RS": "Сербия",
    "TR": "Турция",
    "US": "Соединенные Штаты",
}

SLOVENIAN: Dict[str, str] = {
    "EA":   "Evroobmočje (v tistem trenutku)",
    "EA19": "Evroobmočje (19 držav)",
    "EA18": "Evroobmočje (18 držav)",
    "EU":   "Evropska unija (v tistem trenutku)",
    "EU28": "Evropska unija (28 držav)",
    "BA":   "Bosna in Hercegovina",
    "BE":   "Belgija",
    "BG":   "Bolgarija",
    "CZ":   "Češka",
    "DK":   "Danska",
    "DE":   "Nemčija",
    "EE":   "Estonija",
    "IE":   "Irska",
    "EL":   "Grčija",
    "ES":   "Španija",
    "FR":   "Francija",
    "HR":   "Hrvaška",
    "IT":   "Italija",
    "CY":   "Ciper",
    "LI":   "Liechtenstein",
    "LV":   "Latvija",
    "LT":   "Litva",
    "LU":   "Luksemburg",
    "HU":   "Madžarska",
    "MT":   "Malta",
    "NL":   "Nizozemska",
    "AT":   "Avstrija",
    "PL":   "Poljska",
    "PT":   "Portugalska",
    "RO":   "Romunija",
    "SI":   "Slovenija",
    "SK":   "Slovaška",
    "FI":   "Finska",
    "SE":   "Švedska",
    "UK":   "Združeno kraljestvo",
    "IS":   "Islandija",
    "NO":   "Norveška",
    "CH":   "Švica",
    "MK":   "Severna Makedonija",
    "RS":   "Srbija",
    "TR":   "Turčija",
    "US":   "Združene države",
}
