python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d cphi --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d cphi --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d cphi --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d cphi --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d cphi --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d cphi --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_funding --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_funding --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_funding --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_funding --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_funding --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_funding --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_cost --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_cost --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_cost --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_cost --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_cost --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v full -d health_cost --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d cphi --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d cphi --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d cphi --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d cphi --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d cphi --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d cphi --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_funding --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_funding --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_funding --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_funding --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_funding --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_funding --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_cost --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_cost --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_cost --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_cost --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_cost --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v score -d health_cost --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d cphi --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d cphi --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d cphi --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d cphi --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d cphi --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d cphi --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_funding --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_funding --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_funding --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_funding --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_funding --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_funding --locations SI SK TR UK US all
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_cost --locations AT BE BG CH CY CZ
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_cost --locations DE DK EE EL ES FI
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_cost --locations FR HR HU IE IS IT
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_cost --locations LT LU LV MK MT NL
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_cost --locations NO PL PT RO RS SE
python eunlg/bulk_generate.py -l en -o bulk_out/ -v random -d health_cost --locations SI SK TR UK US all

